// tslint:disable-next-line typedef variable-name (Acts like a type with static properties.)

export const errorCode = {
  GeneralError: "GENERAL_ERROR",
  InvalidId: "INVALID_ID",
  InvalidName: "INVALID_NAME",
  MissingEnv: "MISSING_ENV",
  MissingId: "MISSING_ID",
  InactiveUser: "INACTIVE_USER",
  UnauthorizedUser: "UNAUTHORIZED_USER",
  MissingPermission: "MISSING_PERMISSION",
  MissingBody: "Missing_Body",
  ResourceNotFound: "Resource_Not_Found",
  NoSearchResultsFounds: "No_Search_Results_Founds",
  ResourceNotDeleted: "Resource_Not_Deleted",
  InvalidPatientId: "INVALID_CONSENTINGPARTY_ID",
  InvalidJSON: "InvalidJSON",
  InvalidInput: "InvalidInput",
  InvalidQueryParameterValue: "InvalidQueryParameterValue",
  InvalidRequest: "InvalidRequest",
  PatientNotFound: "ConsentingParty_Not_Found",
  AttachmentNotSaved: "Attachment_Not_Saved",
  AttachmentNotFound: "Attachment_Not_Found",
  ResourceNotSaved: "Resource_Not_Saved",
  unableToGenerateActivities: "unable_To_Generate_Activities",
  ActiveConsentNotFound: "ActiveConsentNotFound",
  InvalidUserId: "INVALID USER ID",
  InvalidMedicationId: "INVALID_Medication_ID",
  InvalidEmail: "INVALID_EMAIL",
  InvalidEmailInviteCode: "Invalid_Email_InviteCode",
  SesError: "SES_FAILURE",
  CognitoError: "COGNITO_ERROR",
  ResourceNotUpdated: "ResourceNotUpdated",
  VersionIdMismatch: "VersionId_Mismatch",
  UnprocessableEntity: "UNPROCESSABLE_ENTITY",
  SequelizeError: "SEQUELIZE_ERROR",
  InvalidCount: "INVALID_COUNT",
  RecordNotFound: "Record_Not_Found"
};
