import { Attachment } from "../../common/attachment";
import { CodeableConcept } from "../../common/codeableConcept";
import { Period } from "../../common/period";
import { Range } from "../../common/range";
import { Ratio } from "../../common/ratio";
import { ReferenceRange } from "../../common/referenceRange";
import { ResourceMetadata } from "../../common/resourceMetadata";
import { SampleData } from "../../common/sampleData";
import { Subject } from "../../common/subject";
import { OriginalSource } from "../../FHIR/elements/originalSource";
import { InformationSource } from "../elements/informationSource";
import { Quantity } from "../elements/quantity";
import { ObservationComponent } from "./observationComponent";

class ObservationDataResource {
  resourceType: string;
  status: string;
  category: CodeableConcept[];
  code: CodeableConcept;
  subject: Subject;
  effectiveDateTime?: string;
  effectivePeriod?: Period;
  issued?: string;
  valueQuantity?: Quantity;
  valueCodeableConcept?: CodeableConcept;
  valueString?: string;
  valueBoolean?: boolean;
  valueRange?: Range;
  valueRatio?: Ratio;
  valueSampledData?: SampleData;
  valueAttachment?: Attachment;
  valueTime?: string;
  valueDateTime?: string;
  valuePeriod?: Period;
  interpretation?: CodeableConcept;
  comment?: string;
  bodySite?: CodeableConcept;
  referenceRange?: ReferenceRange[];
  component?: ObservationComponent[];
  informationSource: InformationSource;
  originalSource?: OriginalSource;
  meta: ResourceMetadata;
}
export { ObservationDataResource };
